In [2]:
import json
from tqdm import tqdm

# 1. Îç∞Ïù¥ÌÑ∞ Î°úÎìú
with open("data/review_0503.json", "r", encoding="utf-8") as f:
    reviews = [json.loads(line) for line in f]

with open("data/user_0503.json", "r", encoding="utf-8") as f:
    users = [json.loads(line) for line in f]

with open("data/business.json", "r", encoding="utf-8") as f:
    businesses = [json.loads(line) for line in f]

In [4]:
import json
import pandas as pd
from tqdm import tqdm


# 2. DataFrameÏúºÎ°ú Î≥ÄÌôò
df_reviews = pd.DataFrame(reviews)
df_users = pd.DataFrame(users)
df_businesses = pd.DataFrame(businesses)

# 3. Ï†ïÎ≥¥ Ï∂úÎ†• Ìï®Ïàò
def print_info(df, name):
    print(f"\nüìå {name} Ï†ïÎ≥¥")
    print("-" * 40)
    print(df.info())
    print(df.head(2))

# 4. Í∞Å ÌååÏùºÏùò Ï†ïÎ≥¥ Ï∂úÎ†•
print_info(df_reviews, "Î¶¨Î∑∞ Îç∞Ïù¥ÌÑ∞")
print_info(df_users, "ÏÇ¨Ïö©Ïûê Îç∞Ïù¥ÌÑ∞")
print_info(df_businesses, "ÏùåÏãùÏ†ê Îç∞Ïù¥ÌÑ∞")

üìå Î¶¨Î∑∞ Îç∞Ïù¥ÌÑ∞ Ï†ïÎ≥¥
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676701 entries, 0 to 676700
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   review_id     676701 non-null  object
 1   user_id       676701 non-null  object
 2   business_id   676701 non-null  object
 3   stars         676701 non-null  int64
 4   useful        676701 non-null  int64
 5   date          676701 non-null  int64
 6   sentiment     676701 non-null  object
 7   cleaned_text  676701 non-null  object
 8   token_length  676701 non-null  int64
dtypes: int64(4), object(5)
memory usage: 46.5+ MB
None
                review_id                 user_id             business_id  \
0  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA
1  JrIxlS1TzJ-iCu79ul40cQ  eUta8W_HdHMXPzLBBZhL1A  04UD14gamNjLY0IDYVhHJg

   stars  useful           date sentiment  \
0      5       1  1420329663000  Positive
1      1       1  1443049831000  Negative

                                        cleaned_text  token_length
0  wow yummy different delicious favorite lamb cu...            24
1  long term frequent customer establishment go o...            32

üìå ÏÇ¨Ïö©Ïûê Îç∞Ïù¥ÌÑ∞ Ï†ïÎ≥¥
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26894 entries, 0 to 26893
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        26894 non-null  object
 1   name           26894 non-null  object
 2   review_count   26894 non-null  int64
 3   useful         26894 non-null  int64
 4   average_stars  26894 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.0+ MB
None
                  user_id   name  review_count  useful  average_stars
0  NIhcRW6DWvk1JQhDhXwgOQ    Lia          2288   12773           3.69
1  RDTVzWPoCeGaUujrHIWRBQ  Jenna           155     222           4.11

üìå ÏùåÏãùÏ†ê Îç∞Ïù¥ÌÑ∞ Ï†ïÎ≥¥
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6911 entries, 0 to 6910
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   6911 non-null   object
 1   name          6911 non-null   object
 2   address       6911 non-null   object
 3   city          6911 non-null   object
 4   state         6911 non-null   object
 5   stars         6911 non-null   float64
 6   review_count  6911 non-null   int64
 7   is_open       6911 non-null   int64
 8   categories    6911 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 486.1+ KB
None
              business_id                name      address          city  \
0  MTSW4McQd7CbVtyjqoe9mw  St Honore Pastries  935 Race St  Philadelphia
1  MUTTqe8uqyMdBl186RmNeA            Tuna Bar  205 Race St  Philadelphia

  state  stars  review_count  is_open  \
0    PA    4.0            80        1
1    PA    4.0           245        1

                                          categories
0  Restaurants, Food, Bubble Tea, Coffee & Tea, B...
1                  Sushi Bars, Restaurants, Japanese

In [13]:
import json
import pandas as pd
from tqdm import tqdm

# 1. JSONL Î°úÎìú Ìï®Ïàò
def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]

# 2. Í≤ΩÎ°ú
review_path = "data/review_0503.json"
user_path = "data/user_0503.json"
business_path = "data/business.json"
output_path = "data/merged_dataset.json"

# 3. Î°úÎî©
reviews = load_jsonl(review_path)
users = load_jsonl(user_path)
businesses = load_jsonl(business_path)

# 4. Îπ†Î•∏ Ï°∞ÌöåÏö© dict
user_dict = {u["user_id"]: u for u in users}
business_dict = {b["business_id"]: b for b in businesses}

# 5. Î≥ëÌï© (Î™®Îì† ÌïÑÎìú Ìè¨Ìï® + prefix Î∂ÄÏó¨)
merged_data = []
skipped = 0

for r in tqdm(reviews, desc="Î≥ëÌï© Ï§ë"):
    uid = r.get("user_id")
    bid = r.get("business_id")

    u = user_dict.get(uid)
    b = business_dict.get(bid)

    if not u or not b:
        skipped += 1
        continue

    # Ïú†Ìö®ÏÑ± ÌïÑÌÑ∞
    if not all([r.get("review_id"), uid, bid, r.get("cleaned_text"), r.get("sentiment")]):
        skipped += 1
        continue

    merged_entry = {}

    # Î¶¨Î∑∞ ÌïÑÎìú
    merged_entry.update(r)

    # user_ prefix Î∂ôÏó¨ÏÑú ÏÇ¨Ïö©Ïûê ÌïÑÎìú Ï∂îÍ∞Ä
    for k, v in u.items():
        merged_entry[f"user_{k}"] = v

    # business_ prefix Î∂ôÏó¨ÏÑú ÏùåÏãùÏ†ê ÌïÑÎìú Ï∂îÍ∞Ä
    for k, v in b.items():
        merged_entry[f"business_{k}"] = v

    merged_data.append(merged_entry)

# 6. Ï†ÄÏû• (JSONL)
with open(output_path, "w", encoding="utf-8") as f:
    for row in merged_data:
        json.dump(row, f, ensure_ascii=False)
        f.write("\n")

# 7. ÌôïÏù∏
print(f"‚úÖ Î≥ëÌï© ÏôÑÎ£å: {output_path}")
print(f"Ï¥ù Î≥ëÌï© Î¶¨Î∑∞ Ïàò: {len(merged_data)}")
print(f"Ï†úÏô∏Îêú Î¶¨Î∑∞ Ïàò: {skipped}")
print(f"ÏµúÏ¢Ö Ïª¨Îüº Ïàò: {len(merged_entry)}")
print("ÏòàÏãú Ïª¨Îüº:", list(merged_entry.keys())[:10], "...")

Î≥ëÌï© Ï§ë: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 676701/676701 [00:02<00:00, 323813.05it/s]

‚úÖ Î≥ëÌï© ÏôÑÎ£å: data/merged_dataset.json
Ï¥ù Î≥ëÌï© Î¶¨Î∑∞ Ïàò: 404121
Ï†úÏô∏Îêú Î¶¨Î∑∞ Ïàò: 272580
ÏµúÏ¢Ö Ïª¨Îüº Ïàò: 23
ÏòàÏãú Ïª¨Îüº: ['review_id', 'user_id', 'business_id', 'stars', 'useful', 'date', 'sentiment', 'cleaned_text', 'token_length', 'user_user_id'] ...

In [14]:
from collections import Counter

# 1. user_idÎ≥Ñ Î¶¨Î∑∞ Ïàò Í≥ÑÏÇ∞
user_review_counts = Counter([row["user_id"] for row in merged_data])

# 2. ÌïÑÌÑ∞ÎßÅ: Î¶¨Î∑∞ 5Í∞ú Ïù¥ÏÉÅÎßå Ìè¨Ìï®
filtered_data = [
    row for row in merged_data
    if user_review_counts[row["user_id"]] >= 5
]

# 3. Ï†ÄÏû•
filtered_output_path = "data/merged_dataset.json"
with open(filtered_output_path, "w", encoding="utf-8") as f:
    for row in filtered_data:
        json.dump(row, f, ensure_ascii=False)
        f.write("\n")

# 4. ÌÜµÍ≥Ñ Ï∂úÎ†•
print("\n‚úÖ ÌïÑÌÑ∞ÎßÅ ÏôÑÎ£å: Î¶¨Î∑∞ 5Í∞ú ÎØ∏Îßå Ïú†Ï†Ä Ï†úÏô∏")
print(f"- Ï¥ù Ïú†Ï†Ä Ïàò: {len(set(user_review_counts))}")
print(f"- Î¶¨Î∑∞ 5Í∞ú ÎØ∏Îßå Ïú†Ï†Ä Ïàò: {sum(1 for v in user_review_counts.values() if v < 5)}")
print(f"- ÏµúÏ¢Ö Ìè¨Ìï® Î¶¨Î∑∞ Ïàò: {len(filtered_data)}")

‚úÖ ÌïÑÌÑ∞ÎßÅ ÏôÑÎ£å: Î¶¨Î∑∞ 5Í∞ú ÎØ∏Îßå Ïú†Ï†Ä Ï†úÏô∏
- Ï¥ù Ïú†Ï†Ä Ïàò: 26894
- Î¶¨Î∑∞ 5Í∞ú ÎØ∏Îßå Ïú†Ï†Ä Ïàò: 0
- ÏµúÏ¢Ö Ìè¨Ìï® Î¶¨Î∑∞ Ïàò: 404121

In [15]:
import json
import pandas as pd

# 1. JSONL ÌååÏùº Í≤ΩÎ°ú
path = "data/merged_dataset.json"  # ÌïÑÏöî Ïãú Í≤ΩÎ°ú ÏàòÏ†ï

# 2. JSONL ÌååÏùº ÏùΩÍ∏∞
with open(path, "r", encoding="utf-8") as f:
    data = [json.loads(line) for line in f]

# 3. pandas DataFrameÏúºÎ°ú Î≥ÄÌôò
df = pd.DataFrame(data)

# 4. Í∏∞Î≥∏ Ï†ïÎ≥¥ Ï∂úÎ†•
print("üìä [Í∏∞Î≥∏ Ï†ïÎ≥¥]")
print(df.info())
print()

# 5. Ïª¨Îüº Î™©Î°ù
print("üßæ [Ïª¨Îüº Î™©Î°ù]")
print(df.columns.tolist())
print()

# 6. ÏòàÏãú Îç∞Ïù¥ÌÑ∞
print("üîç [ÏÉòÌîå Îç∞Ïù¥ÌÑ∞]")
print(df.head(3).to_string(index=False))

üìä [Í∏∞Î≥∏ Ï†ïÎ≥¥]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404121 entries, 0 to 404120
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   review_id              404121 non-null  object
 1   user_id                404121 non-null  object
 2   business_id            404121 non-null  object
 3   stars                  404121 non-null  int64
 4   useful                 404121 non-null  int64
 5   date                   404121 non-null  int64
 6   sentiment              404121 non-null  object
 7   cleaned_text           404121 non-null  object
 8   token_length           404121 non-null  int64
 9   user_user_id           404121 non-null  object
 10  user_name              404121 non-null  object
 11  user_review_count      404121 non-null  int64
 12  user_useful            404121 non-null  int64
 13  user_average_stars     404121 non-null  float64
 14  business_business_id   404121 non-null  object
 15  business_name          404121 non-null  object
 16  business_address       404121 non-null  object
 17  business_city          404121 non-null  object
 18  business_state         404121 non-null  object
 19  business_stars         404121 non-null  float64
 20  business_review_count  404121 non-null  int64
 21  business_is_open       404121 non-null  int64
 22  business_categories    404121 non-null  object
dtypes: float64(2), int64(8), object(13)
memory usage: 70.9+ MB
None

üßæ [Ïª¨Îüº Î™©Î°ù]
['review_id', 'user_id', 'business_id', 'stars', 'useful', 'date', 'sentiment', 'cleaned_text', 'token_length', 'user_user_id', 'user_name', 'user_review_count', 'user_useful', 'user_average_stars', 'business_business_id', 'business_name', 'business_address', 'business_city', 'business_state', 'business_stars', 'business_review_count', 'business_is_open', 'business_categories']

üîç [ÏÉòÌîå Îç∞Ïù¥ÌÑ∞]
             review_id                user_id            business_id  stars  useful          date sentiment                                                                                                                                                                                                  cleaned_text  token_length           user_user_id user_name  user_review_count  user_useful  user_average_stars   business_business_id     business_name business_address business_city business_state  business_stars  business_review_count  business_is_open                    business_categories
8JFGBuHMoiNDyfcxuWNtrA smOvOajNG0lS4Pq7d8g4JQ RZtGWDLCAtuipwaZ-UfjmQ      4       0 1255550234000  Positive                                                                                                                   good foodlove gnocchi marinara baked eggplant appetizer good service slow despite food good            20 smOvOajNG0lS4Pq7d8g4JQ       Meg                176          120                3.46 RZtGWDLCAtuipwaZ-UfjmQ         LaScala's  615 Chestnut St  Philadelphia             PA             3.5                    367                 0     Pizza, Restaurants, Italian, Salad
Xs8Z8lmKkosqW5mw_sVAoA IQsF3Rc6IgCzjVV9DE8KXg eFvzHawVJofxSnD7TgbZtg      5       0 1415806227000  Positive        absolute favorite cafe city black white latte probably good sweet right foam soup good nonsoup people lot space work noise level perfect music perfect level enjoy patron bring dog give business long            34 IQsF3Rc6IgCzjVV9DE8KXg      Dana                182          217                3.41 eFvzHawVJofxSnD7TgbZtg   Good Karma Cafe      928 Pine St  Philadelphia             PA             4.0                    249                 1 Food, Cafes, Coffee & Tea, Restaurants
JBWZmBy69VMggxj3eYn17Q aFa96pz67TwOFu4Weq5Agg kq5Ghhh14r-eCxlVmlyd8w      5       0 1535060378000  Positive boyfriend try deli time today turkey avocado bacon panini ha buffalo chicken wrap definitely return wait food long appreciate lunch hour choose salad soup macaroni sandwich hot food love deli option choose            38 aFa96pz67TwOFu4Weq5Agg     Jenna                 84           75                3.93 kq5Ghhh14r-eCxlVmlyd8w The Coventry Deli   2000 Market St  Philadelphia             PA             4.0                     65                 1  Restaurants, Delis, Salad, Sandwiches

In [ ]:
import json

# 3. Ï§ëÎ≥µ/Î∂àÌïÑÏöîÌïú Ïª¨Îüº Ï†úÍ±∞
drop_cols = ["user_user_id", "business_business_id"]
df.drop(columns=[col for col in drop_cols if col in df.columns], inplace=True)

# 4. Ïª¨Îüº Ïù¥Î¶Ñ Î¶¨ÎÑ§Ïù¥Î∞ç (Î™ÖÌôïÌïòÍ≤å ÌïòÍ∏∞)
df.rename(columns={
    "stars": "review_stars",
    "useful": "review_useful",
    "date": "review_date"
}, inplace=True)

# 5. JSONLÎ°ú Ï†ÄÏû•
output_path = "data/merged_dataset_cleaned.json"
with open(output_path, "w", encoding="utf-8") as f:
    for row in df.to_dict(orient="records"):
        json.dump(row, f, ensure_ascii=False)
        f.write("\n")

# 6. ÏöîÏïΩ Ï∂úÎ†•
print("‚úÖ Ï†ïÎ¶¨ ÏôÑÎ£å: JSONL ÌòïÏãùÏúºÎ°ú Ï†ÄÏû•")
print(f"Ï†ÄÏû• Í≤ΩÎ°ú: {output_path}")
print("Ï¥ù ÏÉòÌîå Ïàò:", len(df))
print("ÏµúÏ¢Ö Ïª¨Îüº Ïàò:", len(df.columns))
print("ÏÉòÌîå Ïª¨Îüº:", df.columns[:10].tolist())

‚úÖ Ï†ïÎ¶¨ ÏôÑÎ£å: JSONL ÌòïÏãùÏúºÎ°ú Ï†ÄÏû•
Ï†ÄÏû• Í≤ΩÎ°ú: data/merged_dataset_cleaned.json
Ï¥ù ÏÉòÌîå Ïàò: 404121
ÏµúÏ¢Ö Ïª¨Îüº Ïàò: 21
ÏÉòÌîå Ïª¨Îüº: ['review_id', 'user_id', 'business_id', 'review_stars', 'review_useful', 'review_date', 'sentiment', 'cleaned_text', 'token_length', 'user_name']

In [19]:
print(df.head(3).to_string(index=False))

             review_id                user_id            business_id  review_stars  review_useful   review_date sentiment                                                                                                                                                                                                  cleaned_text  token_length user_name  user_review_count  user_useful  user_average_stars     business_name business_address business_city business_state  business_stars  business_review_count  business_is_open                    business_categories
8JFGBuHMoiNDyfcxuWNtrA smOvOajNG0lS4Pq7d8g4JQ RZtGWDLCAtuipwaZ-UfjmQ             4              0 1255550234000  Positive                                                                                                                   good foodlove gnocchi marinara baked eggplant appetizer good service slow despite food good            20       Meg                176          120                3.46         LaScala's  615 Chestnut St  Philadelphia             PA             3.5                    367                 0     Pizza, Restaurants, Italian, Salad
Xs8Z8lmKkosqW5mw_sVAoA IQsF3Rc6IgCzjVV9DE8KXg eFvzHawVJofxSnD7TgbZtg             5              0 1415806227000  Positive        absolute favorite cafe city black white latte probably good sweet right foam soup good nonsoup people lot space work noise level perfect music perfect level enjoy patron bring dog give business long            34      Dana                182          217                3.41   Good Karma Cafe      928 Pine St  Philadelphia             PA             4.0                    249                 1 Food, Cafes, Coffee & Tea, Restaurants
JBWZmBy69VMggxj3eYn17Q aFa96pz67TwOFu4Weq5Agg kq5Ghhh14r-eCxlVmlyd8w             5              0 1535060378000  Positive boyfriend try deli time today turkey avocado bacon panini ha buffalo chicken wrap definitely return wait food long appreciate lunch hour choose salad soup macaroni sandwich hot food love deli option choose            38     Jenna                 84           75                3.93 The Coventry Deli   2000 Market St  Philadelphia             PA             4.0                     65                 1  Restaurants, Delis, Salad, Sandwiches